title: The Annotated OpenType Specification
defaults:
  -
    scope:
      path: ""
    values:
      layout: "single"
      read_time: true
      toc: true
      strip_title: true
      sidebar:
        nav: "chapters"

url: http://commontype-standard.github.io/
baseurl: ""

titles_from_headings:
  enabled:     true
  strip_title: true
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-titles-from-headings
  - jekyll-redirect-from
  - jekyll-include-cache
