title: The CommonType Specification
defaults:
  -
    scope:
      path: ""
    values:
      layout: "single"
      read_time: true
      toc: true
      strip_title: true
      sidebar:
        nav: "chapters"

url: http://commontype-standard.github.io/
baseurl: ""

head_scripts:
    - https://hypothes.is/embed.js

titles_from_headings:
  enabled:     true
  strip_title: true

search: true
search_provider: algolia
algolia:
  application_id: H51BAY08M4
  index_name: commontype
  search_only_api_key: 4e79b841a1b7bdb129969ba555656043
  extensions_to_index:
    - md


markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-titles-from-headings
  - jekyll-redirect-from
  - jekyll-include-cache
