name: Rebuild gh-pages
on:
  push:
    branches:
      - source

jobs:
  run:
    name: Rebuild gh-pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get install xsltproc rename docbook-xsl libfile-slurp-perl

    - name: Merge
      uses: devmasx/merge-branch@v1.1.0
      with:
        type: now
        target_branch: 'master'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Rebuild site
      run: make mdhtml DB=/usr/share/xml/docbook/stylesheet/docbook-xsl/

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Rebuild Bot
        author_email: github@github.com
        message: "Rebuild site"
        add: "*.md"
        ref: "master"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
